version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - gem_data:/usr/local/bundle
    environment:
      TZ: "Asia/Tokyo"
    stdin_open: true
    tty: true
volumes:
  gem_data:
